### ISSUE TITLE
콴다는 한국 스타트업입니다

### ISSUE THREAD

**Issue by progresshans** [Like-Lion-NSU/Elementary_School#42]
### 📌 Description

프로젝트 소개에 `“콴다”라는 베트남 어플을 모티브로 삼아`라고 되어있길래...

**Comment by songhyeon99** [comment]
헉.. 그렇군요!! 베트남에서 유명해서 착각했네요.. 자세히 알아봤어야 했는데 실수 했네요.. 알려주셔서 감사합니다:)
